[project]
name = "binary-model"
version = "0.1.0"
description = "binary model for viaspec"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.4.38",
    "jaxopt>=0.8.3",
    "matplotlib>=3.10.0",
    "numpyro>=0.16.1",
]
